[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F"]

[tool.mypy]
python_version = "3.11"
strict = false

[[tool.mypy.overrides]]
module = "alembic_stub.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "pandas_market_calendars.*"
ignore_missing_imports = true
