ALTER TABLE forward_tests RENAME COLUMN roi TO roi_forward;
ALTER TABLE forward_tests RENAME COLUMN hit_pct TO hit_forward;
ALTER TABLE forward_tests RENAME COLUMN dd_pct TO dd_forward;
ALTER TABLE forward_tests RENAME COLUMN last_run TO last_run_at;
ALTER TABLE forward_tests ADD COLUMN status TEXT NOT NULL DEFAULT 'queued';
UPDATE forward_tests SET status='queued' WHERE status IS NULL OR status='pending';
UPDATE forward_tests SET status='ok' WHERE status='done';
ALTER TABLE forward_tests ADD COLUMN next_run_at TEXT;
ALTER TABLE forward_tests ADD COLUMN runs_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE forward_tests ADD COLUMN notes TEXT;
ALTER TABLE forward_tests ADD COLUMN roi_forward REAL;
UPDATE forward_tests SET roi_forward=0.0 WHERE roi_forward IS NULL;
ALTER TABLE forward_tests ADD COLUMN hit_forward REAL;
ALTER TABLE forward_tests ADD COLUMN dd_forward REAL;
ALTER TABLE forward_tests ADD COLUMN rule TEXT;
ALTER TABLE forward_tests ADD COLUMN ticker TEXT;
ALTER TABLE forward_tests ADD COLUMN direction TEXT;
ALTER TABLE forward_tests ADD COLUMN interval TEXT;
ALTER TABLE forward_tests ADD COLUMN created_at TEXT;
UPDATE forward_tests SET created_at=entry_ts WHERE created_at IS NULL;
ALTER TABLE forward_tests ADD COLUMN updated_at TEXT;
UPDATE forward_tests SET updated_at=created_at WHERE updated_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_forward_tests_fav ON forward_tests(fav_id);
